base_dir: /mnt/share/ # where it start in docker env
main_dir: /mnt/share/ # repository in docker env  
genome_dir: genome/ # genome data
sample_dir: samples/ #sample directory
output_dir: outputs/ #output folder
logs_dir: logs/ # for logs...
#---------------Settings----------------------------------------------
#fasta eg: {sample}.read1.fastq.gz
GENOME: resources_broad_hg38_v0_Homo_sapiens_assembly38

KS1: resources_broad_hg38_v0_Homo_sapiens_assembly38.dbsnp138.vcf.gz 
KS2: resources_broad_hg38_v0_Mills_and_1000G_gold_standard.indels.hg38.vcf.gz 
KS3: resources_broad_hg38_v0_Homo_sapiens_assembly38.known_indels.vcf.gz
KS4: resources_broad_hg38_v0_Homo_sapiens_assembly38.dbsnp138.vcf.gz 
KS5: resources_broad_hg38_v0_hapmap_3.3.hg38.vcf.gz 
KS6: resources_broad_hg38_v0_1000G_omni2.5.hg38.vcf.gz 
KS7: 1000G.phase3.integrated.sites_only.no_MATCHED_REV.hg38.vcf  

TARGET: /mnt/share/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chr.bed
GATK: /mnt/share/gatk/gatk-package-4.1.7.0-local.jar 

#___________________________Threading_______________________
BWA_samblaster_sambamba_threads: 8
Call_Variants_threads: 8
