#__________Directories_Paths_________________________________________________________________________________

base_dir: /mnt/ # where it start in docker env
main_dir: /mnt/ # repository in docker env  
genome_dir: genome/ # genome data
sample_dir: samples/ #sample directory
output_dir: outputs/ #output folder
logs_dir: logs/ # for logs


#______________Settings_______________________________________________________________________________________

#fasta eg: {sample}.read1.fastq.gz
GENOME: resources_broad_hg38_v0_Homo_sapiens_assembly38

# Known Sites
KS1: resources_broad_hg38_v0_Homo_sapiens_assembly38.dbsnp138.vcf.gz 
KS2: resources_broad_hg38_v0_Mills_and_1000G_gold_standard.indels.hg38.vcf.gz 
KS3: resources_broad_hg38_v0_Homo_sapiens_assembly38.known_indels.vcf.gz
KS4: resources_broad_hg38_v0_Homo_sapiens_assembly38.dbsnp138.vcf.gz 
KS5: resources_broad_hg38_v0_hapmap_3.3.hg38.vcf.gz 
KS6: resources_broad_hg38_v0_1000G_omni2.5.hg38.vcf.gz 
KS7: 1000G.phase3.integrated.sites_only.no_MATCHED_REV.hg38.vcf  

# Genome target files
TARGET_all_chr: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chr.bed
TARGET_chr1: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chr1.bed
TARGET_chr2: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chr2.bed
TARGET_chr3: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chr3.bed
TARGET_chr4: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chr4.bed
TARGET_chr5: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chr5.bed
TARGET_chr6: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chr6.bed
TARGET_chr7: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chr7.bed
TARGET_chr8: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chr8.bed
TARGET_chr9: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chr9.bed
TARGET_chr10: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chr10.bed
TARGET_chr11: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chr11.bed
TARGET_chr12: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chr12.bed
TARGET_chr13: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chr13.bed
TARGET_chr14: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chr14.bed
TARGET_chr15: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chr15.bed
TARGET_chr16: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chr16.bed
TARGET_chr17: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chr17.bed
TARGET_chr18: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chr18.bed
TARGET_chr19: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chr19.bed
TARGET_chr20: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chr20.bed
TARGET_chr21: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chr21.bed
TARGET_chr22: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chr22.bed
TARGET_chrX: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chrX.bed
TARGET_chrY: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chrY.bed

# GATK Tools
GATK: /mnt/gatk/gatk-package-4.1.7.0-local.jar 


#__________________________Rule_Settings_____________________________________________________________________|

# rule bwa_index (Create index, fasta.sa) ------------\\

bwa_index_partition: 'large' # HPC partition
bwa_index_cpus: 16 # cpus
bwa_index_mem: 64421 # RAM

# rule BWA_samblaster_sambamba  (Align reads to reference) --------\\

BWA_samblaster_sambamba_partition: 'large' # HPC partition
BWA_samblaster_sambamba_threads: 16 # cpus
BWA_samblaster_sambamba_memory: 64421 # RAM

# rule picard_dict (Create sequence dictionary) ------------\\

picard_dict_partition: 'small' # HPC partition
picard_dict_cpus: 4 # cpus
picard_dict_mem: 16040

# rule samtools_index (fasta.fai) ------------\\

samtools_index_partition: 'medium' # HPC partition
samtools_index_cpus: 8 # cpus
samtools_index_mem: 32167 # RAM


# Chromossome Parallelization ------------\\

## partitions:
chr1_partitions: 'small' # 4 cpus 16 gb
chr2_partitions: 'small' # 2 cpus 8gb
chr3_partitions: 'small' # 2 cpus 8gb
chr4_partitions: 'medium' # 2 cpus 8gb
chr5_partitions: 'medium' # 2 cpus 8gb
chr6_partitions: 'medium' # 2 cpus 8gb
chr7_partitions: 'medium' # 2 cpus 8gb
chr8_partitions: 'large' # 1 cpus 4gb
chr9_partitions: 'medium' # 2 cpus 8gb
chr10_partitions: 'medium' # 2 cpus 8gb
chr11_partitions: 'large' # 2 cpus 4gb
chr12_partitions: 'medium' # 2 cpus 8gb
chr13_partitions: 'large' # 1 cpus 4gb
chr14_partitions: 'large' # 1 cpus 4gb
chr15_partitions: 'large' # 1 cpus 4gb
chr16_partitions: 'large' # 2 cpus 8gb
chr17_partitions: 'medium' # 2 cpus 8gb
chr18_partitions: 'large' # 1 cpus 4gb
chr19_partitions: 'large' # 2 cpus 8gb
chr20_partitions: 'large' # 1 cpu 4gb
chr21_partitions: 'large' # 1 cpus 4gb
chr22_partitions: 'large' # 1 cpus 4gb
chrX_partitions: 'large' # 1 cpus 4gb
chrY_partitions: 'large' # 1 cpus 4gb

# cpus:
chr1_cpus: 4
chr2_cpus: 2
chr3_cpus: 2
chr4_cpus: 2 
chr5_cpus: 2
chr6_cpus: 2
chr7_cpus: 2
chr8_cpus: 1
chr9_cpus: 2
chr10_cpus: 2
chr11_cpus: 2
chr12_cpus: 2
chr13_cpus: 1
chr14_cpus: 1
chr15_cpus: 1
chr16_cpus: 2
chr17_cpus: 2
chr18_cpus: 1
chr19_cpus: 2
chr20_cpus: 1
chr21_cpus: 1
chr22_cpus: 1
chrX_cpus: 1
chrY_cpus: 1

# RAM:
chr1_mem: 16040
chr2_mem: 8020
chr3_mem: 8020
chr4_mem: 8020
chr5_mem: 8020
chr6_mem: 8020
chr7_mem: 8020
chr8_mem: 4010
chr9_mem: 8020
chr10_mem: 8020
chr11_mem: 4010
chr12_mem: 8020
chr13_mem: 4010
chr14_mem: 4010
chr15_mem: 4010
chr16_mem: 8020
chr17_mem: 8020
chr18_mem: 4010
chr19_mem: 8020
chr20_mem: 4010
chr21_mem: 4010
chr22_mem: 4010
chrX_mem: 4010
chrY_mem: 4010

# rule Merge_VCFs (merge all vcfs processed independently by chromossome) 

merge_vcf_partition: 'large' # HPC partition
merge_vcf_cpus: 16 # cpus
merge_vcf_mem: 64421

# rule Merge_Recalibrated_VCFs (merge all recalibrated vcfs processed independently by chromossome)

merge_recalibrated_vcf_partition: 'large' # HPC partition
merge_recalibrated_vcf_cpus: 16 # cpus
merge_recalibrated_vcf_mem: 64421

# rule Calculate_Genotype_Posteriors 

genotype_posteriors_partition: 'large' # HPC partition
genotype_posteriors_cpus: 16 # cpus
genotype_posteriors_mem: 64421

