#__________Directories_Paths___________________________________________________________________________

base_dir: /mnt/ # where it start in docker env
main_dir: /mnt/ # repository in docker env  
genome_dir: genome/ # genome data
sample_dir: samples/ #sample directory
output_dir: outputs/ #output folder
logs_dir: logs/ # for logs...


#______________Settings_________________________________________________________________________________

#fasta eg: {sample}.read1.fastq.gz
GENOME: resources_broad_hg38_v0_Homo_sapiens_assembly38


# Known Sites
KS1: resources_broad_hg38_v0_Homo_sapiens_assembly38.dbsnp138.vcf.gz 
KS2: resources_broad_hg38_v0_Mills_and_1000G_gold_standard.indels.hg38.vcf.gz 
KS3: resources_broad_hg38_v0_Homo_sapiens_assembly38.known_indels.vcf.gz
KS4: resources_broad_hg38_v0_Homo_sapiens_assembly38.dbsnp138.vcf.gz 
KS5: resources_broad_hg38_v0_hapmap_3.3.hg38.vcf.gz 
KS6: resources_broad_hg38_v0_1000G_omni2.5.hg38.vcf.gz 
KS7: 1000G.phase3.integrated.sites_only.no_MATCHED_REV.hg38.vcf  

# Genome target file
TARGET: /mnt/samples/nexterarapidcapture_expandedexome_targetedregions_hg19_lifted_hg38_chr.bed

# GATK Tools
GATK: /mnt/gatk/gatk-package-4.1.7.0-local.jar 

#__________Memory______________________________

# Align reads to reference
BWA_samblaster_sambamba_memory: 48 

# Java memory for general tasks
Java_memory: 48

#___________________________Threading_______________________

# Align reads to reference
BWA_samblaster_sambamba_threads: 16

# VCF
Call_Variants_threads: 16
